config/routes.rb
PiouPiou::Application.routes.draw do
  resources(:tweets, { :except => [:edit, :update, :new]})

end

app/models/tweet.rb
# == Schema Information
#
# Table name: tweets
#
#  id         :integer         not null, primary key
#  content    :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class Tweet < ActiveRecord::Base
  attr_accessible :content

  attr_readonly :created_at

  validates :content, presence: :true, length: { minimum: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.order('created_at DESC').page(params[:page]).per(5)
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @tweet = Tweet.find(params[:id])
  end
  # POST /tweets
  # POST /tweets.json
  def create
    @tweets = Tweet.order('created_at DESC').page(params[:page])
    @tweet = Tweet.new(params[:tweet])

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweets_url, notice: 'Tweet successfully created.' }
        format.json { render json: @tweet, status: :created, location: @tweet }
      else
        format.html { render action: "index" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'The tweet has been removed from the database.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Twitter
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  body
    = yield

app/views/tweets/_form.html.slim
= simple_form_for Tweet.new, remote: true do |f|
  div class="form-actions"
    = f.input :content, :label => false, :required => false, as: 'string'
    = f.button :submit, :class => 'btn btn-primary'

app/views/tweets/index.html.slim
 
- model_class = Tweet.new.class
- tweet_model_class = Tweet.new.class


- if @tweet && @tweet.errors.any?
  div class="alert alert-error"
    table
      a class="close" data-dismiss="alert" 
            '×
      - @tweet.errors.messages[:content].each do |message|
        tr
          td
            = message
- flash.each do |name, msg|
  - if msg == 'Tweet successfully created.'
    div class="alert alert-success"
      a class="close" data-dismiss="alert" 
        '×
      = msg
  - elsif msg == 'The tweet has been removed from the database.'
    div class="alert alert-error"
      a class="close" data-dismiss="alert" 
        '×
      = msg


h1
  'Piou-Piou

div class="page-header"
= render :partial => 'form'
div class="page-header"
  div id="tweets-display"
  script id="tweets" type="text/html"
    ul style="list-style-type:none;"
      = render 'tweet'

= paginate @tweets

app/views/tweets/show.html.slim
- model_class = @tweet.class
div class="page-header"
  h1
    =t '.title', :default => model_class.model_name.human

script id="tweets" type="text/html"
  = render 'tweet'
  = link_to t('.back', :default => t("helpers.links.back")), tweets_path, :class => 'btn'
div id="tweets-display"